### ISSUE TITLE
Purpose of this tool

### ISSUE THREAD

**Issue by probonopd** [azubieta/appimage-user-tools#2]
According to its desktop file, the purpose of this tool is to "Manage AppImages on your system". 

In my personal view, the file manager (the FInder for Mac users) is all that's needed to "manage" applications. 

Want to "install" an application? Just drag-and-drop it to a place on your hard disk, on the network, or on an attached external drive. Want to "uninstall" an application? Just drag its icon to the trash can.

Which leads me to believe that we should be working on [that](https://github.com/AppImage/appimaged/issues/30) experience rather than adding tools.

So it'd be helpful to state in the README the idea behind this tool, why it is needed, and which problem it intends to solve.

**Comment by azubieta** [comment]
This tool so far is a demo to asses the idea of providing something similar to the experience that the users get while using the `nx-software-store but from the CLI (actually, it has the same code). So it's more about finding AppImages than about managing them.

**Comment by probonopd** [comment]
Ah, I see. So a command line version of the NX Software Center more or less. Thanks for the explanation.
