### ISSUE TITLE
Some ideas to make this user friendly, less technical and more efficient.

### ISSUE THREAD

**Issue by antony-jr** [azubieta/appimage-user-tools#27]
Something like this,

The developer just need to create a appimage.json in their repo with the details of latest AppImage tag or location. 
 
So the run should be easy as,
```
 $ app run antony-jr@github/ShareMyHost # the repo name is not case sensitive
```

Then to integrate or so called "install",
```
 $ app run+integrate antony-jr@github/ShareMyHost # or
 $ app integrate antony-jr@github/ShareMyHost # and even this
 $ app run+integrate+shortcut antony-jr@github/ShareMyHost 
```

We can also follow the same for opendesktop.org.
```
 $ app run azubieta@od/AppImageInstaller # appname is not case sensitive
```

This will make it similar to snap and flatpak. 

**Also if the AppImage provides the zsync file, it is theoretically possible to construct the file without downloading the entire file by reusing already downloaded appimages.
For example, if you downloaded a Qt app which uses Qt 5.12 and if you want to download a app which is also a Qt app and also uses Qt 5.12 or 5.13 or anything close to 5.12. We can use the data present in the former app to construct the latter app with less bandwidth thus saving time and internet.**

Also to top it off, we can use a Fuse filesystem with some compression to avoid file duplication to reduce disk consumption drastically.

And finally with options to update a single app, We can also have a option to do a system wide update, something like,

```
 $ app evolve # or something like that.
```

**Comment by azubieta** [comment]
This is an interesting idea! Actually I've been thinking about it too :)

> The developer just need to create a appimage.json in their repo with the details of latest AppImage tag or location. 

We can use the GitHub and GitLab REST-APIs to get the latest release

> it is theoretically possible to construct the file without downloading the entire file by reusing already downloaded appimages

In theory, it's possible. But inspecting every downloaded AppImage to find an exactly matching file can be a bit complicated. Consider that they are rarely built using the same binaries.

Regarding the compression, this is already done by appimagetool, and right now is quite good.

**Comment by antony-jr** [comment]
> this is already done by appimagetool, and right now is quite good.

Yes but I was talking about duplication of the whole AppImage itself and not the files inside it. If you inspect, there are a lot of duplication of data between AppImages. Like when you have 10 versions of the same Qt App, you have 10 copies of the same Qt libraries, So if we use a simple dictionary based compression, we could reduce it to 1 copy of the Qt library and 10 copies of the actual main bin files.

**Comment by antony-jr** [comment]
> But inspecting every downloaded AppImage to find an exactly matching file can be a bit complicated.

Yes but we could find Qt library version used by a AppImage with less time compared to running a rolling checksum. Also we can do the same for conda packages. But it's all too theoretical.

**Comment by azubieta** [comment]
@antony-jr I guess that we should discuss the duplication reduction topic in the AppImageKit repo as its a "core" topic.

**Comment by antony-jr** [comment]
Also instead of direct integration, I say we ```run``` the AppImage directly. We cache the AppImage temporarily for the run. And if integrate is used then we actually move it to our compressed filesystem and make start menu icons.

> @antony-jr I guess that we should discuss the duplication reduction topic in the AppImageKit repo as its a "core" topic.

I guess. But using a filesystem imposes that we run a daemon which is not what AppImages stands for. Then it becomes more like snaps. But recently even AppImageLauncher is using a filesystem which makes weird bugs like these -> https://github.com/antony-jr/AppImageUpdaterBridge/issues/29

**Comment by azubieta** [comment]
@antony-jr I guess that it would be good to split this issue in two:
- one for adding support to install AppImages from Gitlab and Github 
- other for binary duplication reduction ideas

**Comment by antony-jr** [comment]
Okay, for starters I think we need the cli app to work like the following, to make it more appealing for developers to adapt. Instead of go ahead and download the binaries from releases we can impose some kind of a single liner like npm packages. Something like this,

Run ShareMyHost using Appimage Installer,

```
 $ app run antony-jr@gh/ShareMyHost
```

To install AppImage Installer, (I guess we can use a URL shortner to make it appealing)

```
 $ bash < (curl -s https://raw.githubusercontent.com/azubieta/appimage-installer/master/install.sh)
```
